# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-03-23 15:50
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clients', '0002_building'),
    ]

    operations = [
        migrations.CreateModel(
            name='dayRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vacancy', models.IntegerField()),
                ('peak', models.IntegerField()),
                ('day', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Space',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('space_type', models.CharField(choices=[('Me', 'Work Seat'), ('We', 'Group Seat'), ('Other', 'Other')], max_length=200)),
                ('space_name', models.CharField(max_length=200)),
                ('space_data', django.contrib.postgres.fields.jsonb.JSONField()),
                ('sensor_id', models.CharField(blank=True, default='', max_length=200)),
                ('building', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clients.Building')),
            ],
        ),
        migrations.CreateModel(
            name='Study',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('study_name', models.CharField(max_length=200, unique=True)),
                ('study_provider', models.CharField(choices=[('Relogix', 'Relogix'), ('CoWorkr', 'CoWorkr'), ('Moby', 'Moby')], max_length=200)),
                ('dynamic', models.BooleanField(default=False)),
                ('building', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clients.Building')),
            ],
        ),
        migrations.AddField(
            model_name='dayrecord',
            name='study',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='space.Study'),
        ),
    ]
