# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-03-23 19:43
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('space', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='spaceRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dateTime', models.DateTimeField()),
                ('occ', models.IntegerField()),
                ('pctMoment', models.FloatField()),
                ('pctSpace', models.FloatField()),
                ('data', django.contrib.postgres.fields.jsonb.JSONField()),
                ('space', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='space.Space')),
                ('study', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='space.Study')),
            ],
        ),
    ]
