# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-03-23 22:54
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('space', '0002_spacerecord'),
    ]

    operations = [
        migrations.AlterField(
            model_name='spacerecord',
            name='data',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=list),
        ),
    ]
