# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-03-23 15:10
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_name', models.CharField(max_length=200)),
                ('client_industry', models.CharField(choices=[('Accounting', 'Accounting'), ('Advertising', 'Advertising'), ('Aerospace/Defense', 'Aerospace/Defense'), ('Architecture/Interior Design', 'Architecture/Interior Design'), ('Automotive', 'Automotive'), ('Banking', 'Banking'), ('Biotechnology', 'Biotechnology'), ('Chemicals', 'Chemicals'), ('Clothing/Textiles', 'Clothing/Textiles'), ('Computer Related', 'Computer Related'), ('Construction/Developer', 'Construction/Developer'), ('Consumables (Food, Tobacco, etc.)', 'Consumables (Food, Tobacco, etc.)'), ('Consumer Products (General)', 'Consumer Products (General)'), ('Cosmetics', 'Cosmetics'), ('Education', 'Education'), ('Electronics', 'Electronics'), ('Employment Agency/Recruiters', 'Employment Agency/Recruiters'), ('Energy (Electricity, Oil, etc.)', 'Energy (Electricity, Oil, etc.)'), ('Engineering', 'Engineering'), ('Entertainment (Film, TV, Music, etc.)', 'Entertainment (Film, TV, Music, etc.)'), ('Environmental', 'Environmental'), ('Financial Services (Non-banking)', 'Financial Services (Non-banking)'), ('Fine Arts (Galleries, Museums)', 'Fine Arts (Galleries, Museums)'), ('Government', 'Government'), ('Health Care Related', 'Health Care Related'), ('Import/Export', 'Import/Export'), ('Industrial Products (Heavy Industry)', 'Industrial Products (Heavy Industry)'), ('Information Services/Market Research', 'Information Services/Market Research'), ('Insurance', 'Insurance'), ('Jewelry & Furs', 'Jewelry & Furs'), ('Law', 'Law'), ('Management Consulting', 'Management Consulting'), ('Marketing/Public Relations', 'Marketing/Public Relations'), ('Non-profit', 'Non-profit'), ('Office Products', 'Office Products'), ('Pharmaceuticals', 'Pharmaceuticals'), ('Printing/Reproductions', 'Printing/Reproductions'), ('Publishing', 'Publishing'), ('Real Estate', 'Real Estate'), ('Restaurant/Hotel', 'Restaurant/Hotel'), ('Retail Sales', 'Retail Sales'), ('Security/Private Investigation', 'Security/Private Investigation'), ('Shipping/Delivery', 'Shipping/Delivery'), ('Technology', 'Technology'), ('Telecommunications', 'Telecommunications'), ('Travel Related (Airlines, Agents, Mass Transit)', 'Travel Related (Airlines, Agents, Mass Transit)'), ('Warehouse/Distribution', 'Warehouse/Distribution')], max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_name', models.CharField(max_length=200, unique=True)),
                ('project_type', models.CharField(choices=[('Strategy', 'Strategy'), ('Change', 'Change'), ('Experience', 'Experience')], max_length=200)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clients.Client')),
            ],
        ),
    ]
